# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stud.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
    ]
